# Generated by Django 4.2.16 on 2026-02-09 20:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='CSV or Excel file', upload_to='uploads/data/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx', 'xls'])])),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, default=dict, help_text='Detailed error information for failed rows')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Upload',
                'verbose_name_plural': 'Data Uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='PDF document', upload_to='uploads/documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='uploads.dataupload')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supporting Document',
                'verbose_name_plural': 'Supporting Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('data', models.JSONField(help_text='Row data as JSON')),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_errors', models.JSONField(blank=True, default=list, help_text='List of validation errors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='uploads.dataupload')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded Record',
                'verbose_name_plural': 'Uploaded Records',
                'ordering': ['row_number'],
                'indexes': [models.Index(fields=['data_upload', 'row_number'], name='uploads_upl_data_up_305f95_idx'), models.Index(fields=['is_valid'], name='uploads_upl_is_vali_0a8083_idx')],
                'unique_together': {('data_upload', 'row_number')},
            },
        ),
        migrations.AddIndex(
            model_name='dataupload',
            index=models.Index(fields=['-created_at'], name='uploads_dat_created_240489_idx'),
        ),
        migrations.AddIndex(
            model_name='dataupload',
            index=models.Index(fields=['status'], name='uploads_dat_status_bae74f_idx'),
        ),
        migrations.AddIndex(
            model_name='dataupload',
            index=models.Index(fields=['uploaded_by'], name='uploads_dat_uploade_bfb1af_idx'),
        ),
    ]
