# Generated by Django 4.2.16 on 2026-02-09 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('UPLOAD', 'Uploaded'), ('DOWNLOAD', 'Downloaded'), ('EXPORT', 'Exported'), ('LOGIN', 'Logged In'), ('LOGOUT', 'Logged Out'), ('PERMISSION_CHANGE', 'Permission Changed'), ('STATUS_CHANGE', 'Status Changed')], max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('entity_type', models.CharField(help_text='Type of entity affected (User, DataUpload, etc.)', max_length=100)),
                ('entity_id', models.CharField(blank=True, help_text='ID of the affected entity', max_length=100)),
                ('entity_repr', models.CharField(blank=True, help_text='String representation of the entity', max_length=255)),
                ('description', models.TextField(help_text='Human-readable description of what happened')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Detailed changes (old_value, new_value)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (IP address, user agent, etc.)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx'), models.Index(fields=['user', '-timestamp'], name='audit_audit_user_id_ea8c9f_idx'), models.Index(fields=['action', '-timestamp'], name='audit_audit_action_e33994_idx'), models.Index(fields=['entity_type', '-timestamp'], name='audit_audit_entity__8f5d70_idx')],
            },
        ),
    ]
